# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61571edfebdb0b1a2b7c5ee067a235258d5079a6e5c617d29f06b9c4506e07cdfd8e523fcf8f7bd88bc0b642efa72753aadb5fb36f25370364d3cf35fadae73e

test:
  secret_key_base: 085d15459dd2ef8233b1acab68964f58147cb1a37032a6ae27ddb6f908100e14cc068190aaa1da36da71a69b153343a749a0a2ab13e0032b74cab2f41c476e6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
